apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      restartPolicy: Always
      containers:
        - image: sample-app
          imagePullPolicy: IfNotPresent
          name: sample-app
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 8080
